title: Geek-O-System
email: michael@riesd.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://devblog.riesd.com"
twitter_username: mmmries
github_username:  mmmries

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
tag_page_layout: tag_page
tag_page_dir: tag
google_analytics: UA-41023244-1
